// scout_clients/static/scout_clients/react/components/spots-list.jsx
import React, { Component } from 'react';
import axios from "axios";

const styles = {
  marginBottom: '25px'
}

export class SpotsList extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
                  title: 'All Spooots',
                  loading: true,
                  spots: []
                 };
  }

  componentDidMount() {
    this.state.loading = true;
    axios
      .get('http://curry.aca.uw.edu:8000/spots.json')
      .then(response => {
        this.setState({
          spots: response.data,
          loading: false
        });
      })
      .catch(error => {
        console.log(error)
      });
  }

  render() {

    let content;

    if (this.state.loading) {
      content = <div className="pt-3">Loading...</div>;
    } else {
      content =
        <ul className="p-0">
          {this.state.spots.map( spot => {
            return (
              <li key={spot.id} className="media text-muted pt-3">
                   <img src="http://via.placeholder.com/32x32" alt="..." className="mr-2 rounded" />
                   <p className="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                     <strong className="d-block text-gray-dark">{spot.name }</strong>
                     {spot.building_name }<br/>
                     {spot.latitude }, {spot.longitude }</p>
              </li>
            );
          })}
        </ul>
    }

    return (
     <div style={styles}>
       <div>
         <small className="text-muted">The following component...</small>
       </div>
       <div style={styles} className="my-3 p-3 bg-white rounded box-shadow">
         <h6 className="border-bottom border-gray pb-2 mb-0">All Spots</h6>
         {content}
       </div>
     </div>
    );

  }
}

// scout_clients/static/scout_clients/vue/components/spots-list.vue
<template>
  <div>

    <div>
      <small class="text-muted">The following component...</small>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">

      <h6 class="border-bottom border-gray pb-2 mb-0">{{title}}</h6>

      <div class="pt-3" v-if="loading">
        Loading.....
      </div>
      <ul v-else class="p-0">
          <li v-for="spot in spots" class="media text-muted pt-3">
            <img src="http://via.placeholder.com/32x32" alt="" class="mr-2 rounded">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              <strong class="d-block text-gray-dark">{{ spot.name }}</strong>
              {{ spot.building_name }}<br/>
              {{spot.latitude }}, {{ spot.longitude }}
            </p>
         </li>
      </ul>
    </div>
  </div>
</template>

<script>
  import axios from 'axios';
  export default {
    data () {
      return {
        title: 'All Spots',
        loading: true,
        spots: []
      }
    },
    mounted () {
      this.loading = true;
      axios
        .get('http://curry.aca.uw.edu:8000/spots.json')
        .then(response => {
          this.spots = response.data
          this.loading = false
        })
        .catch(error => {
          console.log(error)
          this.errored = true
        });
    }
  }
</script>

<style>

</style>
