// scout_clients/static/scout_clients/vuejs/button-counter.vue
<template>
  <div style="margin-bottom:25px;">
    <button v-on:click="count++">You clicked me {{ count }} times. (single file component)</button>
  </div>
</template>
<script>
  export default {
    data: function () {
      return {
        count: 0
      }
    }
  }
</script>
<style lang="scss">
#ButtonCounter {
  // some scss rules
}
</style>

// scout_clients/static/scout_clients/react/components/button-counter.jsx
import React, { Component } from 'react';

export class ButtonCounter extends React.Component {

  constructor(props) {
        super(props);
        this.state = { count: 0 };
        this.incrementCount = this.incrementCount.bind(this);
    }

    incrementCount(){
      this.setState({count: this.state.count + 1});
    }

    render() {
        return (
          <div>
            <button onClick={ this.incrementCount }>You clicked me {this.state.count} times.. (exported react component)</button>
          </div>
        );
    }
};
